import { TextField, InputLabel } from '@mui/material';
export declare const rootClassName = "dot-text-field";
export declare const rootSelectClassName = "dot-select-field";
export declare const labelClassName = "dot-input-label";
export declare const errorClassName = "dot-error";
export declare const warningClassName = "dot-warning";
export declare const successClassName = "dot-success";
export declare const adornmentIconClassName = "dot-adornment-icon";
export declare const fieldsetClassName = "MuiOutlinedInput-notchedOutline";
export declare const StyledAdornment: import("styled-components").StyledComponent<import("@mui/material/OverridableComponent").OverridableComponent<import("@mui/material").InputAdornmentTypeMap<{}, "div">>, any, {}, never>;
export declare const StyledInputLabel: import("styled-components").StyledComponent<typeof InputLabel, any, {}, never>;
export declare const StyledTextFieldContainer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const StyledTextField: import("styled-components").StyledComponent<typeof TextField, any, {}, never>;
