import { ComponentMeta, Story } from '@storybook/react';
import { AutoCompleteOption, AutoCompleteProps } from './AutoComplete';
import { AutoCompleteWithRenderOption } from './Autocomplete.stories.data';
declare const _default: ComponentMeta<(<T extends AutoCompleteOption>({ ListboxComponent, actionItem, ariaLabel, autoFocus, className, "data-testid": dataTestId, defaultValue, dense, disabled, disablePortal, endAdornmentTooltip, error, filterSelectedOptions, freesolo, group, helperText, inputId, inputRef, label, loading, maxHeight, multiple, onBlur, onChange, onClose, onInputChange, onOpen, open, options, persistentLabel, placeholder, readOnly, renderOption, renderTags, required, size, value, warning, }: AutoCompleteProps<T>) => JSX.Element)>;
export default _default;
export declare const Default: any;
export declare const WithActionItem: any;
export declare const WithCustomActionItem: Story<AutoCompleteProps>;
export declare const WithAsyncLoad: Story<AutoCompleteProps>;
declare type AutoCompleteWithRenderOptionProps = AutoCompleteProps<AutoCompleteWithRenderOption>;
export declare const WithRenderOption: Story<AutoCompleteWithRenderOptionProps>;
export declare const WithChipError: Story<AutoCompleteProps>;
export declare const WithoutChips: Story<AutoCompleteWithRenderOptionProps>;
export declare const WithNullAsValue: Story<AutoCompleteProps>;
export declare const WithMaxHeight: any;
export declare const WithCustomBlur: Story<AutoCompleteProps>;
export declare const WithReadOnly: any;
export declare const WithWarning: any;
export declare const WithError: any;
export declare const WithLabel: any;
export declare const WithPersistentLabel: any;
export declare const WithFixedVirtualList: Story<AutoCompleteProps>;
