import { ComponentMeta, Story } from '@storybook/react';
import { LinearProgressProps } from './LinearProgress';
declare const _default: ComponentMeta<({ ariaLabel, color, className, "data-testid": dataTestId, value, valueBuffer, variant, }: LinearProgressProps) => JSX.Element>;
export default _default;
export declare const Default: Story<LinearProgressProps>;
export declare const WithDeterminateVariant: any;
export declare const WithBufferVariant: any;
export declare const WithQueryVariant: any;
export declare const WithPrimaryColor: any;
export declare const WithSecondaryColor: any;
export declare const WithErrorColor: any;
export declare const WithWarningColor: any;
export declare const WithPurpleColor: any;
