import { ComponentMeta, Story } from '@storybook/react';
import { ButtonToggleProps } from './';
declare const _default: ComponentMeta<({ ariaLabel, buttonOptions, className, color, "data-testid": dataTestId, disableFocusRipple, disableRipple, exclusive, onChange, orientation, size, value, }: ButtonToggleProps) => JSX.Element>;
export default _default;
export declare const Default: Story<ButtonToggleProps>;
export declare const WithTooltip: Story<ButtonToggleProps>;
export declare const WithDifferentValueTypes: Story<ButtonToggleProps>;
export declare const WithExclusivity: Story<ButtonToggleProps>;
export declare const WithSmallSize: Story<ButtonToggleProps>;
export declare const WithLargeSize: Story<ButtonToggleProps>;
export declare const WithPrimaryColor: Story<ButtonToggleProps>;
